builds:
- env:
  - CGO_ENABLED=0
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

nfpms:
  - name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    homepage:  https://github.com/wpjunior/tsuru-prometheus-wrapper
    description: Utility to deploy prometheus on tsuru
    maintainer: Wilson Júnior <wilsonpjunior@gmail.com>
    license: MIT
    vendor:
    formats:
    - deb
    - rpm
